stages:
  - test
  - build
  - deploy
  - release

before_script:
  - export TERRAFORM_MODULE_SYSTEM=digitalocean
  - export TF_VAR_SPACES_ACCESS_KEY_ID=$ACCESS_KEY
  - export TF_VAR_SPACES_SECRET_ACCESS_KEY=$SECRET_KEY
  - exprot TF_VAR_DO_TOKEN=$DO_API_KEY

include:
  - component: $CI_SERVER_FQDN/ci/semantic-release/semantic-release-simple@0.1.4
  - template: Terraform-Module.gitlab-ci.yml
