name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1

      - name: Format check
        run: tofu fmt -check -recursive

      - name: Init
        run: tofu init -backend=false

      - name: Validate
        run: tofu validate

      - name: Test
        run: tofu test
